---
driver:
  name: vagrant
  ssh:
    insert_key: false

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6

suites:
  - name: default
    driver:
      network:
        - ['private_network', {ip: '33.33.33.9'}]
    run_list:
      - recipe[emacs]
      - recipe[chef-provisioning-node::default]
      - recipe[test::setup_ssh_keys]
      - recipe[test::delivery-cluster]
      - recipe[test::delivery-cli]
    attributes:

  <%  10.upto(14) do |n| %>
  - name: delivery-<%= n %>
    run_list:

    driver:
      vm_hostname: delivery-<%= n %>.example.com
      network:
        - ['private_network', {ip: '33.33.33.<%= n %>'}]
      customize:
        memory: 2048
        cpus: 2
    attributes:
  <% end %>
